ebook_metadata:
  title: ༄༅། །དབུ་རྫོགས་ལྟ་མགུར་ཟབ་མོ་ཞེས་བྱ་བ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ།
  - ༧ལྕང་སྐྱ་རོལ་པའི་རྡོ་རྗེ།
  - ༧ཀུན་མཁྱེན་མི་ཕམ།
  - ༧ཞེ་ཆེན་མཁན་པོ་གང་ཤར་དབང་པོ།
  - རྩ་བ། ༧ལྕང་སྐྱ་རོལ་པའི་རྡོ་རྗེ།
  - ས་བཅད། ༧ཀུན་མཁྱེན་མི་ཕམ།
  - ྩ་བ། ༧ཀུན་མཁྱེན་མི་ཕམ་ཕྱོགས་ལས་རྣམ་རྒྱལ།
  - ་བཅད། ༧མཁན་ཆེན་གང་ཤར་དབང་པོ།
  - ཛད་པ་པོ། ༧མཁན་ཆེན་གང་ཤར་དབང་པོ།
  - ུས་དམན་དགེ་འདུན་ནས་བསྒྲིགས།
  sku: TSD-KG-02
  layers:
  - book_title
  - author
  - chapter_title
  - tsawa
  - quotation
  - sabche
  - yigchung
web_metadata:
  title:
    en: A Commentary on the Profound Spiritual Songs of the Middle Way and Dzogchen
    bo: དབུ་རྫོགས་ལྟ་མགུར་ཟབ་མོ་ཞེས་བྱ་བ་བཞུགས་སོ།།
  collection:
    en: Khenpo Gangshar Series–  Book 2
    bo: མཁན་པོ་གང་ཤར་གསུང་འབུམ།–  དེབ། ༢
  author:
    en: Authors:Changkya Rolpai Dorje,Jamgon Mipham Gyatso,Shechen Khenpo Gangshar
      Wangpo
    bo: མཁྱེན་ཆེན་གང་ཤར་དབང་པོ།,འཇམ་མགོན་མི་ཕམ་རྒྱ་མཚོ།,ལྕང་སྐྱ་རོལ་པའི་རྡོ་རྗེ།
  pusblisher:
    en: Tsadra Foundation Publishing
    bo: ཙཱ་འདྲ་ཐེབས་རྩ་ཚོགས་པ།
  sku: TSD-KG-02
  category:
    en: ''
    bo: ''
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: TSD-KG-02.epub
  description:
    en: ''
    bo: ''
